%% Method 1
syms phi th psi b1 b2 b3
R1 = [...
    1           0           0;...
    0           cos(phi)    sin(phi);...
    0          -sin(phi)    cos(phi)]; 
R2 = [...
    cos(th)     0  -sin(th);...
    0           1   0;...
    sin(th)     0   cos(th)];
R3 = [...
     cos(psi)    sin(psi)     0;...
    -sin(psi)    cos(psi)     0;...
     0           0            1]; 

R = simplify(R1*R2*R3);
b = [b1; b2; b3];

a = simplify(R.'*b);
a3 = a(3);

a_prime = simplify(R2.'*R1.'*b);
a2_prime = a_prime(2);

a_pprime = simplify(R1.'*b);
a1_pprime = a_pprime(1);
