function [mu_t, sigma_t,K] = extended_kalman_filter(mu_tmin1, sigma_tmin1, u_tmin1, z_t, m, sigma_r, sigma_phi,Ts,alpha)
    th = mu_tmin1(3);
    vt = u_tmin1(1);
    omegat = u_tmin1(2);
    Gt = [...
        1   0   -(vt/omegat)*cos(th) + (vt/omegat)*cos(th + omegat*Ts);...
        0   1   -(vt/omegat)*sin(th) + (vt/omegat)*sin(th + omegat*Ts);...
        0   0                           1];
    Vt = [...
        (-sin(th) + sin(th + omegat*Ts))/omegat     vt*(sin(th) - sin(th + omegat*Ts))/(omegat^2) + vt*cos(th + omegat*Ts)*Ts/omegat;...
        (cos(th) - cos(th + omegat*Ts))/omegat      -vt*(cos(th) - cos(th + omegat*Ts))/(omegat^2) + vt*sin(th + omegat*Ts)*Ts/omegat;...
        0                                           Ts];
    Mt = [alpha(1)*vt^2 + alpha(2)*omegat^2     0;...
        0                                   alpha(3)*vt^2 + alpha(4)*omegat^2];
    mu_tbar = mu_tmin1 +...
        [-(vt/omegat)*sin(th) + (vt/omegat)*sin(th + omegat*Ts);...
        (vt/omegat)*cos(th) - (vt/omegat)*cos(th + omegat*Ts);...
        omegat*Ts];
    sigma_tbar = Gt*sigma_tmin1*Gt.' + Vt*Mt*Vt.';
    Qt = [sigma_r^2     0;...
        0               sigma_phi^2];
    K = zeros(3,2,size(m,1));
    for i = 1:size(z_t,1)/2
        z_ti = [z_t(i);z_t(i+size(z_t,1)/2)]; %z_t is [R1;R2;R3;phi1;phi2;phi3]
        q = (m(i,1) - mu_tbar(1))^2 + (m(i,2)-mu_tbar(2))^2;
        z_thati = [...
            sqrt(q);...
            atan2(m(i,2) - mu_tbar(2), m(i,1) - mu_tbar(1)) - mu_tbar(3)];
        H_ti = [...
            -(m(i,1) - mu_tbar(1))/sqrt(q)    -(m(i,2) - mu_tbar(2))/sqrt(q)    0;...
            (m(i,2) - mu_tbar(2))/q             -(m(i,1) - mu_tbar(1))/q          -1];
        S_ti = H_ti*sigma_tbar*H_ti.' + Qt;
        K_ti = sigma_tbar*H_ti.'/(S_ti);
        mu_tbar = mu_tbar + K_ti*(z_ti - z_thati);
        sigma_tbar = (eye(3) - K_ti*H_ti)*sigma_tbar; 
        K(:,:,i) = K_ti;
    end
    mu_t = mu_tbar;
    sigma_t = sigma_tbar; 
end

