%% Problem 1
%Define State Space System
A = [...
    2   0   0;...
    0   -1  0;...
    0   0   -1];
B = [...
    1   0;...
    1   0;...
    0   1];
C = [...
    1   0   2;...
    0   -1  0];
D = [...
    1   0;...
    1   0];
%Question a: Poles of the system and multiplicity of each pole.
eig(A)
%Question b: Invariant zeros of the system
syms s
P = [s*eye(3) - A, B; -C, D];
det(P)
%Question c: Transmission zeros of the system
G = C*inv(s*eye(3)-A)*B + D
det(G)

%% Problem 2
A = [...
    -1  0   0;...
    0   -2  0;...
    0   0   -2];
B = [...
    2   -2;...
    -2  4;...
    -4  2];
C = [...
    1   1   0;...
    1   0   1];
D = [...
    0   0;...
    0   0];
%Question a:
syms s
P = [s*eye(3)-A, B; -C, D];
trans_zero = tzero(A,B,C,D);
ic = null(subs(P,s,trans_zero));
x0 = -ic(1:3)
u0 = ic(4:5)
%Question b:
y = C*x0 + D*u0

