function [R] = calc_R(axis,angle)
%calc_R: Calculate a rotation matrix (dynamics backwards from robotics)
%   axis = string: 'x', 'y', or 'z' - which axis you are rotating about
%   angle = angle you are rotating in degrees

if axis == 'x'
    R = [...
        1           0               0;...
        0           cosd(angle)     sind(angle);...
        0           -sind(angle)    cosd(angle)]; %from X'Y'Z' to X"Y"Z" 
end

if axis == 'y'
    R = [...
        cosd(angle)     0   -sind(angle);...
        0               1   0;...
        sind(angle)     0   cosd(angle)];
end

if axis == 'z'
    R = [...
        cosd(angle)     sind(angle)     0;...
        -sind(angle)    cosd(angle)     0;...
        0               0               1]; %from XYZ to X'Y'Z'
end

end

