syms psi th phi psidot thdot phidot wx wy wz m  g Fx Fy Fz Vx Vy Vz

R1 = [...
    1           0               0;...
    0           cos(phi)     sin(phi);...
    0           -sin(phi)    cos(phi)]; 

R2 = [...
    cos(th)     0   -sin(th);...
    0               1   0;...
    sin(th)     0   cos(th)];

R3 = [...
    cos(psi)     sin(psi)     0;...
    -sin(psi)    cos(psi)     0;...
    0               0               1]; 

simplify(R1*R2*R3*[0;0;psidot] + R1*R2*[0; thdot; 0] + R1*[phidot;0;0]);

simplify(inv([-sin(th) 0 1; cos(th)*sin(phi) cos(phi) 0; cos(th)*cos(phi) -sin(phi) 0])*[wx; wy; wz]);

F = simplify([Fx;Fy;Fz] + R1*R2*R3*[0;0;-m*g]);

P = simplify(R3.'*R2.'*R1.'*[Vx;Vy;Vz])